### ISSUE TITLE
 F-droid release crashes immediately

### ISSUE THREAD

**Issue by cvzi** [rmtheis/android-ocr#40]
When I try to start the app, it just shows a dialog "Unfortunately, OCR Test has stopped." Logcat is empty.

This only happens with the version from [F-droid](https://f-droid.org/wiki/page/edu.sfsu.cs.orange.ocr).
If I install it from Google Play Store or compile it myself, it works fine.

My system is Android 4.4.2, API 19

**Comment by pauljie018** [comment]
This might be because your opening the OCR TEST[app by eyes-two] not the main app. OR your library is out of date.
See this : https://github.com/rmtheis/android-ocr/issues/34

The real problem that I don't know why and How is the : 
A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 26018 (Thread-1019) in Android 4.3 Devices

**Comment by cvzi** [comment]
I installed the app from F-droid repository, I did not change anything. I simply start the icon that is added to the homescreen.

**Comment by rmtheis** [comment]
I'm not familiar with F-droid. Maybe you can open this issue with that project.
