### ISSUE TITLE
I am wondering if version 0.6.0 (Aug. 13, 2017) is available.

### ISSUE THREAD

**Issue by robATgit** [rmtheis/android-ocr#73]
Hi
Re: android-ocr

I am wondering if version 0.6.0 (Aug. 13, 2017) is available. I have installed this version on my phone and it works VERY well.
I wanted to set it up for a friend so that he can scan in 2-3 line address labels. That way he won't have to type them in.
But I need to modify the code so that I can automate the process a but more, else I would use what I have as it is.

The version here seems to be V 0.5.14 (May 11, 2014)

Thanks in advance
Robert.

**Comment by rmtheis** [comment]
No, I don't plan to release it, because the expansion file code adds some complexity that I don't want to write instructions for or support, and the expansion file itself is too large for Github.

That said, the OCR code is the same in 0.6.0 as in the current version, it just uses tess-two 8.0.0 instead of tess-two 6.0.4. So the current version should meet your needs for the address label scanner I believe.
